import type { ServiceCategoryView, ProviderView, BusinessView } from "@/lib/mockAppClient";

// ── Static Categories — full subcategory lists matching HomeScreen.tsx ───────
export const STATIC_CATEGORIES: ServiceCategoryView[] = [
    {
        id: "repair",
        label: "Ev, Tamirat & Tadilat",
        description: "Evinizdeki tamirat ve tadilat işleri için uzmanlar",
        lane: "services",
        icon: "🔧",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Boya ve Badana", "Su Tesisatı ve Onarım", "Elektrik Tesisatı ve Arıza",
            "Mobilya Montajı ve Tamiri", "Kombi ve Radyatör Bakımı", "Klima Montajı ve Servisi",
            "Mutfak ve Banyo Tadilatı", "Parke ve Zemin Döşeme", "Fayans ve Seramik İşleri",
            "Çilingir ve Kapı Kilidi Değişimi", "Kapı ve Pencere Tamiri", "Kartonpiyer ve Asma Tavan",
            "Alçıpan ve Bölme Duvar", "Duvar Kağıdı Uygulama", "Dış Cephe Boya ve Yalıtım",
            "Çatı Tamiri ve İzolasyon", "Panjur ve Sineklik Montajı", "Bahçe Düzenleme ve Peyzaj",
            "Havuz Bakımı ve Onarımı", "Akıllı Ev Sistemleri Kurulumu", "Kamera ve Güvenlik Sistemleri",
            "Mermer ve Doğal Taş İşleme", "Ahşap Doğrama ve Marangozluk", "Metal ve Demir Doğrama İşleri",
            "Tıkanıklık Açma ve Pimaş Yıkama", "Cam Balkon ve Kış Bahçesi Sistemleri", "Stor Perde ve Korniş Montajı",
            "Tv ve Uydu Sistemleri Kurulumu", "Beyaz Eşya Tamiri ve Kurulumu", "Ev ve Ofis İlaçlama",
            "Kalorifer ve Doğalgaz Tesisatı", "Çelik Kapı Montajı ve Onarımı", "Merdiven ve Küpeşte Tasarımı",
            "Şömine ve Barbekü Yapımı", "Asansör Bakım ve Onarım",
        ],
    },
    {
        id: "digital",
        label: "Dijital & Yazılım Hizmetleri",
        description: "Web, mobil uygulama, yapay zeka ve yazılım çözümleri",
        lane: "services",
        icon: "💻",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Web Tasarım ve Geliştirme", "Mobil Uygulama Geliştirme", "E-ticaret Sistemleri Kurulumu ve Yönetimi",
            "Masaüstü Yazılım Geliştirme", "Oyun Geliştirme", "Veri Bilimi ve Analitiği",
            "Yapay Zeka ve Makine Öğrenmesi Çözümleri", "Siber Güvenlik ve Sızma Testi", "Bulut Bilişim ve Sunucu Yönetimi",
            "Veritabanı Yönetimi ve Tasarımı", "API Geliştirme ve Entegrasyon", "Blokzincir ve Akıllı Kontrat Geliştirme",
            "Gömülü Sistemler ve IoT Yazılımları", "QA ve Yazılım Test Otomasyonu", "UI/UX Tasarımı ve Prototipleme",
            "SEO ve Teknik Web Analizi", "DevSecOps ve Sistem Otomasyonu", "CRM ve ERP Sistemleri Danışmanlığı",
            "Veri Kurtarma ve Yedekleme Çözümleri", "Yazılım Mimari Danışmanlığı", "No-Code ve Low-Code Uygulama Geliştirme",
            "Büyük Veri İşleme ve Yönetimi", "Doğal Dil İşleme Çözümleri", "Bilgisayarlı Görü Sistemleri",
            "Robotik Süreç Otomasyonu", "Yazılım Dokümantasyonu ve Teknik Yazarlık", "Dijital Erişilebilirlik Danışmanlığı",
            "E-posta Sunucusu ve Altyapı Yönetimi", "Mobil Oyun Optimizasyonu", "SaaS Ürün Geliştirme ve Yönetimi",
            "Mikroservis Mimarisi Dönüşümü", "Yazılım Modernizasyonu ve Legacy Kod Güncelleme", "Açık Kaynak Kodlu Yazılım Özelleştirme",
            "Sanal Gerçeklik ve Artırılmış Gerçeklik Yazılımları", "Veri Görselleştirme ve Dashboard Tasarımı",
        ],
    },
    {
        id: "creative",
        label: "Yaratıcı İşler & Medya",
        description: "Tasarım, fotoğrafçılık, video ve içerik üretimi",
        lane: "services",
        icon: "🎨",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Logo ve Kurumsal Kimlik Tasarımı", "Sosyal Medya İçerik Tasarımı", "Video Kurgu ve Post Prodüksiyon",
            "2D ve 3D Animasyon Tasarımı", "Hareketli Grafikler ve Motion Design", "Dijital İllüstrasyon ve Çizim",
            "Ürün ve Ticari Fotoğrafçılık", "Etkinlik ve Konser Fotoğrafçılığı", "Metin Yazarlığı ve Blog İçerik Üretimi",
            "Sosyal Medya Yönetimi ve Danışmanlığı", "Seslendirme, Dublaj ve Ses Tasarımı", "Ambalaj ve Etiket Tasarımı",
            "Katalog, Dergi ve Kitap Mizanpajı", "Afiş, Broşür ve İlan Tasarımı", "NFT ve Kripto Sanat Üretimi",
            "YouTube Kanal Danışmanlığı ve Kurgusu", "Drone Çekimi ve Hava Fotoğrafçılığı", "Marka Danışmanlığı ve Konumlandırma",
            "Podcast Prodüksiyonu ve Düzenleme", "Karakter Tasarımı ve Modelleme", "Kullanıcı Deneyimi ve Arayüz Tasarımı Görselleştirme",
            "Moda ve Reklam Fotoğrafçılığı", "Kurumsal Tanıtım Filmi Hazırlama", "Storyboard ve Senaryo Yazımı",
            "Renk Düzenleme ve Color Grading", "Görsel Efekt ve VFX Uygulamaları", "Web Sitesi Görsel Arayüz Tasarımı",
            "Marka İsimlendirme ve Slogan Çalışması", "Sunum ve Deck Tasarımı", "Mimari Görselleştirme ve Render",
            "İç Mekan ve Dekorasyon Fotoğrafçılığı", "Dijital Pazarlama Görselleri ve Banner Tasarımı", "Tipografi ve Yazı Fontu Tasarımı",
            "Müzik Prodüksiyonu ve Jingle Yapımı", "Sanal Gerçeklik ve Artırılmış Gerçeklik İçerik Tasarımı",
        ],
    },
    {
        id: "education",
        label: "Eğitim, Ders & Mentorluk",
        description: "Özel ders, mentorluk ve kariyer danışmanlığı",
        lane: "services",
        icon: "🎓",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Matematik ve Fen Bilimleri Özel Ders", "Yabancı Dil Eğitimi ve Konuşma Pratiği", "Yazılım ve Programlama Eğitimi",
            "YKS, LGS ve KPSS Sınav Koçluğu", "TOEFL, IELTS ve Dil Sınavlarına Hazırlık", "Enstrüman ve Müzik Teorisi Dersleri",
            "Güzel Sanatlar ve Çizim Teknikleri Eğitimi", "Kariyer Planlama ve Mentorluk", "Kişisel Gelişim ve Yaşam Koçluğu",
            "İşletme Yönetimi ve Girişimcilik Mentorluğu", "Finansal Okuryazarlık ve Borsa Eğitimi", "Veri Analizi ve İleri Seviye Excel Dersleri",
            "Dijital Pazarlama ve SEO Mentorluğu", "Hitabet, Diksiyon ve Etkili İletişim Eğitimi", "Grafik Tasarım ve Görsel Sanatlar Kursu",
            "Dans, Pilates ve Yoga Eğitimi", "Satranç ve Akıl Oyunları Mentorluğu", "Çocuklar İçin Robotik Kodlama ve STEM Eğitimi",
            "Akademik Danışmanlık ve Makale Yazım Desteği", "Fotoğrafçılık ve Video Kurgu Atölyesi", "Gastronomi ve Yemek Pişirme Teknikleri",
            "El Sanatları, Örgü ve Hobi Atölyeleri", "Sporcu Beslenmesi ve Performans Koçluğu", "Mindfulness ve Meditasyon Rehberliği",
            "Ebeveyn Danışmanlığı ve Çocuk Gelişimi Eğitimi", "Yaratıcı Yazarlık ve Editörlük Mentorluğu", "Sunum Teknikleri ve Topluluk Önünde Konuşma",
            "E-ticaret ve Global Satış Danışmanlığı", "Yapay Zeka Okuryazarlığı ve Prompt Mühendisliği", "Oyun Tasarımı ve Unity/Unreal Engine Mentorluğu",
            "Diyetisyen Onaylı Sağlıklı Yaşam Koçluğu", "Teknik Çizim ve 3D Modelleme Eğitimi", "Portfolyo Geliştirme ve Sanat Okulu Hazırlık",
            "Siber Güvenlik ve Network Altyapı Eğitimi", "Blockchain ve Web3 Teknolojileri Mentorluğu",
        ],
    },
    {
        id: "cleaning",
        label: "Temizlik & Düzenleme",
        description: "Ev, ofis ve kurumsal temizlik hizmetleri",
        lane: "services",
        icon: "✨",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Ev Temizliği", "Ofis ve İş Yeri Temizliği", "İnşaat Sonrası Temizlik",
            "Dış Cephe ve Cam Temizliği", "Koltuk ve Döşeme Yıkama", "Halı Yıkama",
            "Perde ve Stor Temizliği", "İlaçlama ve Pest Kontrol", "Dezenfeksiyon Hizmetleri",
            "Bahçe Temizliği ve Atık Toplama", "Havuz Temizliği", "Apartman ve Site Temizliği",
            "Kuru Temizleme ve Ütüleme", "Giysi ve Gardırop Düzenleme", "Mutfak ve Kiler Düzenleme",
            "Depo ve Garaj Düzenleme", "Ev Taşıma Öncesi ve Sonrası Temizlik", "Baca Temizliği",
            "Su Deposu Temizliği", "Yat ve Tekne Temizliği", "Araç Detaylı Temizlik ve Oto Kuaför",
            "Endüstriyel Alan Temizliği", "Okul ve Eğitim Alanları Temizliği", "Sağlık Kuruluşları Temizliği",
            "Restoran ve Mutfak Detaylı Temizliği", "Evsel Atık ve Moloz Kaldırma", "Yangın ve Su Baskını Sonrası Temizlik",
            "Eşya Paketleme ve İstifleme", "Dijital Düzenleme ve Arşivleme", "Kütüphane ve Doküman Düzenleme",
            "Mobilya ve Yüzey Cilalama", "Zemin Parlatma ve Kristalize Cila", "Çamaşır Yıkama ve Katlama",
            "Yerleşim ve Alan Optimizasyonu", "Minimalist Yaşam Danışmanlığı",
        ],
    },
    {
        id: "delivery",
        label: "Lojistik, Paket & Destek",
        description: "Kurye, nakliyat ve teslimat hizmetleri",
        lane: "services",
        icon: "🚚",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Şehir İçi Kurye ve Paket Teslimatı", "Market ve Bakkal Alışverişi", "Evden Eve Nakliye ve Taşımacılık",
            "Parça Eşya Taşıma", "Evrak, Dosya ve Pasaport Teslimatı", "Eczane Alışverişi ve İlaç Temini",
            "Çiçek ve Hediye Gönderimi", "Mobilya ve Beyaz Eşya Nakliyesi", "Motorlu Kurye Hizmetleri",
            "Bisikletli Kurye ve Çevreci Teslimat", "Kişisel Alışveriş Asistanlığı", "Kargo Teslim Alımı ve İade Yönetimi",
            "Havaalanı Transfer ve Karşılama Desteği", "Sıra Bekleme Hizmetleri", "Ağır Eşya Taşıma ve Yükleme Yardımı",
            "Moloz ve Eski Eşya Atımı", "Su ve Tüp Siparişi Teslimatı", "Şehirler Arası Kargo ve Lojistik Koordinasyonu",
            "Hassas ve Kırılacak Eşya Taşımacılığı", "Soğuk Zincir ve Gıda Taşımacılığı", "Depolama ve Ardiye Hizmetleri",
            "Günlük veya Saatlik Kurye Kiralama", "Acil Paket ve Ekspres Servis", "Etkinlik ve Fuar Ekipmanları Taşımacılığı",
            "Valiz ve Bagaj Taşıma Hizmeti", "Mağaza Teslimat Takibi ve Teslim Alımı", "Kurumsal Dağıtım ve Saha Operasyonları",
            "Gümrükleme ve Mevzuat Takip Desteği", "Araç Çekici ve Yol Yardım Koordinasyonu", "Yurt Dışı Paket Gönderim Danışmanlığı",
            "Dağıtımlı Broşür ve İlan Servisi", "Gece Teslimat ve Nöbetçi Kurye", "Özel Gün ve Organizasyon Lojistiği",
            "Hafif Ticari Araçla Nakliye", "Tedarik Zinciri ve Stok Yönetim Desteği",
        ],
    },
    {
        id: "beauty",
        label: "Kişisel Bakım & Sağlık",
        description: "Sağlık, güzellik ve wellness hizmetleri",
        lane: "services",
        icon: "💆",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Berber ve Erkek Kuaförü", "Kadın Kuaförü ve Saç Tasarımı", "Cilt Bakımı ve Estetik",
            "Makyaj ve Kalıcı Makyaj Hizmetleri", "Manikür, Pedikür ve Nail Art", "Masaj ve Spa Hizmetleri",
            "Lazer Epilasyon ve Ağda", "Kişisel Spor Eğitmeni", "Yoga ve Pilates Eğitimi",
            "Diyetisyen ve Beslenme Danışmanlığı", "Psikolog ve Terapi Hizmetleri", "Fizyoterapi ve Rehabilitasyon",
            "Hasta ve Yaşlı Bakım Refakatçiliği", "Çocuk Bakımı ve Oyun Ablası", "Medikal Ayak Bakımı",
            "Diş Beyazlatma ve Ağız Bakım Danışmanlığı", "İmaj ve Stil Danışmanlığı", "Yaşam Koçluğu ve Mental Sağlık Desteği",
            "Mindfulness ve Meditasyon Rehberliği", "Fonksiyonel Tıp ve Bütüncül Sağlık Danışmanlığı", "Doğum Koçluğu ve Hamilelik Eğitimi",
            "Uyku Koçluğu", "Nefes Terapisi ve Teknikleri", "Alternatif Tıp Uygulamaları",
            "Aromaterapi ve Doğal Ürün Danışmanlığı", "Evde Serum ve Enjeksiyon Hizmetleri", "Protez Saç ve Saç Ekimi Danışmanlığı",
            "İşitme Cihazı Bakım ve Danışmanlığı", "Konuşma Terapisi", "Ergoterapi Hizmetleri",
            "Güzellik Uzmanlığı Eğitimi ve Danışmanlığı", "Bağımlılık Danışmanlığı", "Cinsel Terapi ve Aile Danışmanlığı",
            "Online Sağlık ve Wellness Danışmanlığı", "Kişisel Laboratuvar Testi Takibi ve Check-up Danışmanlığı",
        ],
    },
    {
        id: "consulting",
        label: "Profesyonel & Danışmanlık",
        description: "Hukuk, muhasebe, strateji ve iş danışmanlığı",
        lane: "services",
        icon: "💼",
        preferredProviderType: "BOTH",
        subCategories: [
            "Avukatlık ve Hukuki Danışmanlık", "Muhasebe ve Mali Müşavirlik", "Çeviri ve Tercümanlık",
            "Emlak ve Gayrimenkul Danışmanlığı", "Mimari Proje ve Tasarım", "İç Mimari Danışmanlığı",
            "İnsan Kaynakları ve İşe Alım Danışmanlığı", "İş Stratejisi ve Yönetim Danışmanlığı", "Pazarlama ve Satış Stratejisi",
            "Finansal Planlama ve Yatırım Danışmanlığı", "Hibe ve Teşvik Danışmanlığı", "Marka ve Patent Vekilliği",
            "Sigorta Danışmanlığı", "İş Sağlığı ve Güvenliği Danışmanlığı", "Çevre Danışmanlığı ve Atık Yönetimi",
            "BT ve Teknoloji Danışmanlığı", "Halkla İlişkiler ve İtibar Yönetimi", "Etkinlik ve Organizasyon Danışmanlığı",
            "Dış Ticaret ve Gümrük Danışmanlığı", "Proje Yönetimi ve Planlama", "İstatistiksel Veri Analizi ve Raporlama",
            "Teknik Yazarlık ve Şartname Hazırlama", "Siyasi Danışmanlık ve Kamuoyu Araştırması", "Enerji Verimliliği Danışmanlığı",
            "Kalite Yönetim Sistemleri ve ISO Danışmanlığı", "Tedarik Zinciri ve Satın Alma Danışmanlığı", "Hukuki ve Yeminli Tercüme",
            "Dış Kaynaklı Finans ve CFO Hizmetleri", "Perakende ve Mağazacılık Danışmanlığı", "Yurt Dışı Eğitim Danışmanlığı",
            "Kurumsal Sosyal Medya Stratejisi", "Kriz Yönetimi ve İletişimi", "Müşteri Deneyimi ve Memnuniyet Analizi",
            "Sürdürülebilirlik ve ESG Danışmanlığı", "Sanal Asistanlık ve İdari Destek",
        ],
    },
    {
        id: "pets",
        label: "Evcil Hayvan Hizmetleri",
        description: "Köpek, kedi ve diğer evcil hayvanlar için bakım ve eğitim",
        lane: "services",
        icon: "🐾",
        preferredProviderType: "INDIVIDUAL",
        subCategories: [
            "Köpek Gezdirme", "Evcil Hayvan Bakıcılığı ve Konaklama", "Evcil Hayvan Kuaförü ve Bakımı",
            "Veterinerlik ve Sağlık Danışmanlığı", "Temel ve İleri Seviye Köpek Eğitimi", "Evcil Hayvan Taşıma ve Pet Taksi",
            "Akvaryum Kurulumu ve Bakımı", "Evcil Hayvan Fotoğrafçılığı", "Beslenme ve Diyet Danışmanlığı",
            "Davranış Bozuklukları ve Rehabilitasyon", "Kedi Bakımı ve Oyun Arkadaşlığı", "Kuş Bakımı ve Kafes Temizliği",
            "Sürüngen ve Egzotik Hayvan Bakımı", "Evcil Hayvan Atık Temizliği", "Mikroçip Kaydı ve Künye Hizmetleri",
            "Kayıp Evcil Hayvan Arama Desteği", "Evcil Hayvan İlk Yardım Eğitimi", "Ameliyat Sonrası Evde Bakım Destek",
            "Yaşlı Evcil Hayvan Bakımı", "Evcil Hayvan Oteli ve Pansiyonu", "Evde Banyo ve Tırnak Kesimi",
            "Evcil Hayvan Sahiplendirme Danışmanlığı", "Evcil Hayvan Dostu Mekan ve Seyahat Planlama", "Sosyalleşme ve Oyun Grupları Organizasyonu",
            "Evcil Hayvan Güvenlik Filesi ve Kapı Montajı", "Akvaryum ve Teraryum Tasarımı", "Evcil Hayvan Masajı ve Wellness",
            "Terapi Hayvanı Eğitimi", "Organik Mama ve Ödül Maması Hazırlama", "Şov ve Yarışma Hazırlık Eğitimi",
            "Evcil Hayvan Veda ve Cenaze Hizmetleri", "Kemirme ve Tırmalama Sorunları Çözümü", "Tuvalet Eğitimi Danışmanlığı",
            "Evcil Hayvan Ürünleri ve İlaç Temini", "Irk Seçimi ve Hazırlık Danışmanlığı",
        ],
    },
    {
        id: "events",
        label: "Etkinlik & Organizasyon",
        description: "Düğün, doğum günü ve kurumsal etkinlik organizasyonu",
        lane: "services",
        icon: "🎉",
        preferredProviderType: "BOTH",
        subCategories: [
            "Düğün, Nişan ve Davet Organizasyonu", "Doğum Günü ve Parti Planlama", "Kurumsal Etkinlik ve Toplantı Yönetimi",
            "Ses, Işık ve Görüntü Sistemleri Kiralama", "Catering ve Yemek Hizmetleri", "DJ ve Canlı Müzik Performansı",
            "Sahne Kurulumu ve Dekor Tasarımı", "Davetiye Tasarımı ve Matbaa İşleri", "Etkinlik Fotoğrafçılığı ve Video Çekimi",
            "Host, Hostes ve Karşılama Ekibi", "Mekan Süsleme ve Çiçek Tasarımı", "Havai Fişek ve Lazer Gösterileri",
            "Palyaço ve Çocuk Eğlence Hizmetleri", "Fuar Stand Tasarımı ve Kurulumu", "Konser ve Festival Organizasyonu",
            "Seminer, Konferans ve Workshop Planlama", "Kına Gecesi ve Bekarlığa Veda Organizasyonu", "Mezuniyet Töreni ve Balo Hazırlığı",
            "Masa ve Sandalye Kiralama", "Çadır ve Portatif Yapı Kurulumu", "Sanatçı Menajerliği ve Booking",
            "Promosyon Ürünleri ve Etkinlik Kitleri", "Kokteyl ve Bar Servisi", "Dijital Etkinlik ve Webinar Teknik Desteği",
            "Güvenlik ve Giriş Kontrol Hizmetleri", "Temizlik ve Etkinlik Sonrası Toplama", "LCV ve Davetli Takibi",
            "VIP Transfer ve Protokol Hizmetleri", "Kostüm ve Ekipman Kiralama", "Tur ve Gezi Organizasyonu",
            "Sergi ve Galeri Kuratörlüğü", "Spor Müsabakaları ve Turnuva Yönetimi", "Ödül Töreni ve Plaket Hazırlığı",
            "Teknik Prodüksiyon ve Yayın Yönetimi", "Etkinlik Danışmanlığı ve Bütçe Planlama",
        ],
    },
];

// ── Static Providers ─────────────────────────────────────────────────────────
export const STATIC_PROVIDERS: ProviderView[] = [
    {
        id: "p-001", displayName: "Mehmet Yılmaz", providerType: "Serbest Uzman",
        headline: "Boya, badana ve iç cephe yenileme uzmanı",
        summary: "15 yıllık deneyimle İstanbul genelinde kaliteli boya ve badana hizmetleri. Hızlı, temiz, garantili iş.",
        categoryIds: ["repair"], locationScope: "Kadıköy, İstanbul",
        rating: 4.8, completedJobs: 187, responseTime: "30 dk", servesNearby: true,
        tags: ["boya", "badana", "iç cephe", "dış cephe", "duvar", "boyacı"],
        photoUrl: "", priceRange: "₺800 - ₺3.500 / oda", distanceKm: 1.4,
    },
    {
        id: "p-002", displayName: "Ali Kara", providerType: "Serbest Uzman",
        headline: "Su tesisatı, klima montajı ve kombi servisi",
        summary: "Tesisatçılık ve klima servisi konularında 10 yıl deneyim. Arıza tespiti, yeni kurulum, bakım.",
        categoryIds: ["repair"], locationScope: "Üsküdar, İstanbul",
        rating: 4.6, completedJobs: 243, responseTime: "15 dk", servesNearby: true,
        tags: ["su tesisatı", "klima", "montaj", "arıza", "tıkanıklık", "kombi"],
        photoUrl: "", priceRange: "₺400 - ₺2.200 / işlem", distanceKm: 2.8,
    },
    {
        id: "p-003", displayName: "Ayşe Demir", providerType: "Serbest Uzman",
        headline: "Profesyonel ev ve ofis temizliği",
        summary: "Detaylı ev temizliği, post-tadilat temizlik ve ofis temizliği. Ürünlerimi getiririm, güvenilir referanslarım var.",
        categoryIds: ["cleaning"], locationScope: "Beşiktaş, İstanbul",
        rating: 4.9, completedJobs: 312, responseTime: "10 dk", servesNearby: true,
        tags: ["ev temizliği", "ofis", "post-tadilat", "koltuk yıkama", "halı", "düzenleme"],
        photoUrl: "", priceRange: "₺350 - ₺900 / seans", distanceKm: 0.7,
    },
    {
        id: "p-004", displayName: "Can Öztürk", providerType: "Serbest Uzman",
        headline: "Full-stack web geliştirici ve React uzmanı",
        summary: "Next.js, React, Node.js ile modern web uygulamaları. 7 yıl yazılım deneyimi, 50+ başarılı proje.",
        categoryIds: ["digital"], locationScope: "Şişli, İstanbul",
        rating: 4.7, completedJobs: 54, responseTime: "2 saat", servesNearby: false,
        tags: ["web geliştirme", "react", "next.js", "full-stack", "tasarım", "frontend"],
        photoUrl: "", priceRange: "₺4.000 - ₺18.000 / proje", distanceKm: 4.2,
    },
    {
        id: "p-005", displayName: "Zeynep Şahin", providerType: "Serbest Uzman",
        headline: "Grafik tasarımcı — logo, marka ve sosyal medya",
        summary: "Kurumsal kimlik, logo tasarımı ve sosyal medya içerikleri. Adobe CC ile 8 yıl deneyim.",
        categoryIds: ["creative"], locationScope: "Beşiktaş, İstanbul",
        rating: 4.8, completedJobs: 98, responseTime: "1 saat", servesNearby: false,
        tags: ["logo", "marka", "grafik", "sosyal medya", "kurumsal kimlik", "tasarım"],
        photoUrl: "", priceRange: "₺1.500 - ₺8.000 / proje", distanceKm: 1.1,
    },
    {
        id: "p-006", displayName: "Burak Çelik", providerType: "Serbest Uzman",
        headline: "YKS ve LGS matematik — 9 yıllık deneyimli öğretmen",
        summary: "Lise ve ortaokul düzeyinde matematik, fizik ve kimya özel dersleri. Evde veya online.",
        categoryIds: ["education"], locationScope: "Ataşehir, İstanbul",
        rating: 4.9, completedJobs: 420, responseTime: "aynı gün", servesNearby: true,
        tags: ["matematik", "fen bilimleri", "YKS", "LGS", "özel ders", "sınav koçluğu"],
        photoUrl: "", priceRange: "₺300 - ₺600 / saat", distanceKm: 6.3,
    },
    {
        id: "p-007", displayName: "Fatma Yıldız", providerType: "Serbest Uzman",
        headline: "Köpek bakıcısı, gezdirme ve temel eğitim",
        summary: "Evde veya dışarıda köpek gezdirme, bakım ve temel eğitim. Tüm ırklar kabul.",
        categoryIds: ["pets"], locationScope: "Sarıyer, İstanbul",
        rating: 4.7, completedJobs: 89, responseTime: "45 dk", servesNearby: true,
        tags: ["köpek", "gezdirme", "bakım", "eğitim", "kedi", "pet"],
        photoUrl: "", priceRange: "₺200 - ₺500 / gün", distanceKm: 8.5,
    },
    {
        id: "p-008", displayName: "Hakan Arslan", providerType: "Serbest Uzman",
        headline: "Düğün ve etkinlik organizatörü",
        summary: "Düğün, nişan, doğum günü ve kurumsal etkinliklerde kapsamlı organizasyon. 200+ etkinlik deneyimi.",
        categoryIds: ["events"], locationScope: "Bakırköy, İstanbul",
        rating: 4.6, completedJobs: 67, responseTime: "2 saat", servesNearby: false,
        tags: ["düğün", "organizasyon", "etkinlik", "nişan", "doğum günü", "davet"],
        photoUrl: "", priceRange: "₺5.000 - ₺25.000 / etkinlik", distanceKm: 9.1,
    },
    {
        id: "p-009", displayName: "Elif Kaya", providerType: "Serbest Uzman",
        headline: "Kadın kuaförü ve saç bakım uzmanı — eve gelen",
        summary: "Saç kesim, boyama, kalıcı makyaj ve cilt bakımı için evinize geliyorum. 8 yıl salon deneyimi.",
        categoryIds: ["beauty"], locationScope: "Maltepe, İstanbul",
        rating: 4.8, completedJobs: 264, responseTime: "20 dk", servesNearby: true,
        tags: ["kuaför", "saç", "makyaj", "cilt bakımı", "manikür", "kalıcı makyaj"],
        photoUrl: "", priceRange: "₺250 - ₺900 / seans", distanceKm: 3.6,
    },
    {
        id: "p-010", displayName: "İbrahim Güneş", providerType: "Serbest Uzman",
        headline: "Motor kurye — ekspres ve aynı gün teslimat",
        summary: "İstanbul içi motorlu kurye hizmetleri. Evrak, paket, çiçek ve kargo teslimatı. 7/24 müsait.",
        categoryIds: ["delivery"], locationScope: "Fatih, İstanbul",
        rating: 4.5, completedJobs: 1240, responseTime: "5 dk", servesNearby: true,
        tags: ["kurye", "teslimat", "motor", "ekspres", "paket", "acil"],
        photoUrl: "", priceRange: "₺80 - ₺350 / teslimat", distanceKm: 2.1,
    },
    {
        id: "p-011", displayName: "Seda Yılmaz", providerType: "Serbest Uzman",
        headline: "Diyetisyen — kilo kontrolü ve sağlıklı beslenme",
        summary: "Kişiye özel beslenme programı, diyet takibi ve sağlıklı yaşam rehberliği. Online görüşme imkânı.",
        categoryIds: ["beauty"], locationScope: "Nişantaşı, İstanbul",
        rating: 4.9, completedJobs: 178, responseTime: "1 saat", servesNearby: false,
        tags: ["diyetisyen", "beslenme", "kilo", "diyet", "sağlıklı yaşam", "wellness"],
        photoUrl: "", priceRange: "₺500 - ₺1.500 / ay", distanceKm: 5.4,
    },
    {
        id: "p-012", displayName: "Murat Doğan", providerType: "Serbest Uzman",
        headline: "Elektrikçi — tesisatlı arıza, sigorta ve pano",
        summary: "Ev ve ofis elektrik tesisatı, arıza tespiti, pano yenileme ve aydınlatma. Acil servis 7/24.",
        categoryIds: ["repair"], locationScope: "Bağcılar, İstanbul",
        rating: 4.7, completedJobs: 341, responseTime: "20 dk", servesNearby: true,
        tags: ["elektrik", "tesisatı", "arıza", "sigorta", "pano", "elektrikçi"],
        photoUrl: "", priceRange: "₺300 - ₺1.800 / iş", distanceKm: 7.3,
    },
    {
        id: "p-013", displayName: "Deniz Aydın", providerType: "Serbest Uzman",
        headline: "Ürün ve moda fotoğrafçısı, drone operatörü",
        summary: "E-ticaret ürün çekimi, moda ve reklam fotoğrafçılığı, drone ile hava çekimi.",
        categoryIds: ["creative"], locationScope: "Levent, İstanbul",
        rating: 4.8, completedJobs: 145, responseTime: "2 saat", servesNearby: false,
        tags: ["fotoğraf", "ürün", "moda", "drone", "reklam", "stüdyo"],
        photoUrl: "", priceRange: "₺1.200 - ₺6.000 / gün", distanceKm: 4.9,
    },
    {
        id: "p-014", displayName: "Özlem Çevik", providerType: "Serbest Uzman",
        headline: "İngilizce özel ders ve IELTS hazırlık koçu",
        summary: "Yetişkin ve çocuklara İngilizce konuşma pratiği, IELTS, TOEFL hazırlık.",
        categoryIds: ["education"], locationScope: "Avcılar, İstanbul",
        rating: 4.6, completedJobs: 195, responseTime: "aynı gün", servesNearby: false,
        tags: ["ingilizce", "IELTS", "TOEFL", "yabancı dil", "dil eğitimi", "konuşma pratiği"],
        photoUrl: "", priceRange: "₺350 - ₺700 / saat", distanceKm: 12.5,
    },
    {
        id: "p-015", displayName: "Tarık Polat", providerType: "Serbest Uzman",
        headline: "Klima montaj ve bakım servisi — tüm markalar",
        summary: "Split, duvar tipi, kaset tipi klimaların kurulum, bakım, gaz dolumu ve arıza.",
        categoryIds: ["repair"], locationScope: "Pendik, İstanbul",
        rating: 4.5, completedJobs: 278, responseTime: "30 dk", servesNearby: false,
        tags: ["klima", "montaj", "bakım", "servis", "gaz", "iklimlendirme"],
        photoUrl: "", priceRange: "₺450 - ₺1.200 / klima", distanceKm: 15.2,
    },
    {
        id: "p-016", displayName: "Burcu Aslan", providerType: "Serbest Uzman",
        headline: "Pilates ve yoga eğitmeni — eve gelen özel ders",
        summary: "Evinizde veya stüdyomuzda reformer pilates, yoga ve esneme dersleri.",
        categoryIds: ["beauty", "education"], locationScope: "Etiler, İstanbul",
        rating: 4.9, completedJobs: 203, responseTime: "1 saat", servesNearby: true,
        tags: ["pilates", "yoga", "eğitmen", "spor", "esneme", "meditasyon"],
        photoUrl: "", priceRange: "₺400 - ₺850 / seans", distanceKm: 3.2,
    },
    {
        id: "p-017", displayName: "Kerem Kılıç", providerType: "Serbest Uzman",
        headline: "Python & AI geliştirici — veri bilimi ve otomasyon",
        summary: "Makine öğrenmesi modelleri, veri analizi, RPA otomasyonu ve API geliştirme.",
        categoryIds: ["digital"], locationScope: "Maslak, İstanbul",
        rating: 4.8, completedJobs: 38, responseTime: "3 saat", servesNearby: false,
        tags: ["python", "yapay zeka", "makine öğrenmesi", "veri bilimi", "otomasyon", "AI"],
        photoUrl: "", priceRange: "₺8.000 - ₺30.000 / proje", distanceKm: 6.7,
    },
    {
        id: "p-018", displayName: "Pınar Başer", providerType: "Serbest Uzman",
        headline: "İç mimar — mekan tasarımı ve dekorasyon",
        summary: "Konsept tasarımdan uygulamaya kadar bütüncül iç mekan hizmetleri. 3D çizim, malzeme seçimi.",
        categoryIds: ["consulting", "creative"], locationScope: "Beyoğlu, İstanbul",
        rating: 4.7, completedJobs: 62, responseTime: "2 saat", servesNearby: false,
        tags: ["iç mimari", "dekorasyon", "tasarım", "mimari proje", "mekan", "3D"],
        photoUrl: "", priceRange: "₺3.500 - ₺12.000 / oda", distanceKm: 2.4,
    },
    {
        id: "p-019", displayName: "Ahmet Yıldırım", providerType: "Serbest Uzman",
        headline: "Parke ve laminant döşeme uzmanı",
        summary: "Ahşap parke, laminant zemin, SPC ve PVC döşeme. İstanbul geneli. Ürün temin dahil.",
        categoryIds: ["repair"], locationScope: "Esenyurt, İstanbul",
        rating: 4.6, completedJobs: 156, responseTime: "aynı gün", servesNearby: false,
        tags: ["parke", "laminant", "zemin döşeme", "zemin", "SPC", "döşeme"],
        photoUrl: "", priceRange: "₺180 - ₺380 / m²", distanceKm: 18.4,
    },
    {
        id: "p-020", displayName: "Gül Özdemir", providerType: "Serbest Uzman",
        headline: "Masaj ve spa — evinize gelen profesyonel terapi",
        summary: "İsveç masajı, derin doku, Taylandlı ve aromaterapi masajı. Evinizde rahatlatıcı spa deneyimi.",
        categoryIds: ["beauty"], locationScope: "Suadiye, İstanbul",
        rating: 4.8, completedJobs: 148, responseTime: "2 saat", servesNearby: true,
        tags: ["masaj", "spa", "terapi", "aromaterapi", "wellness", "gevşeme"],
        photoUrl: "", priceRange: "₺500 - ₺1.200 / seans", distanceKm: 4.1,
    },
    {
        id: "p-021", displayName: "Emre Şen", providerType: "Serbest Uzman",
        headline: "SEO ve dijital pazarlama danışmanı",
        summary: "Web sitesi SEO optimizasyonu, Google Ads, sosyal medya reklam yönetimi.",
        categoryIds: ["digital", "consulting"], locationScope: "Mecidiyeköy, İstanbul",
        rating: 4.7, completedJobs: 73, responseTime: "1 saat", servesNearby: false,
        tags: ["SEO", "dijital pazarlama", "google ads", "sosyal medya", "web analizi"],
        photoUrl: "", priceRange: "₺2.500 - ₺8.000 / ay", distanceKm: 5.8,
    },
    {
        id: "p-022", displayName: "Neslihan Kurt", providerType: "Serbest Uzman",
        headline: "İngilizce ve Almanca sertifikalı çevirmen",
        summary: "Hukuki, teknik ve edebi metin çevirisi. Yeminli tercümanlık.",
        categoryIds: ["consulting"], locationScope: "Üsküdar, İstanbul",
        rating: 4.9, completedJobs: 287, responseTime: "2 saat", servesNearby: false,
        tags: ["çeviri", "tercümanlık", "ingilizce", "almanca", "hukuki", "yeminli tercüme"],
        photoUrl: "", priceRange: "₺0.08 - ₺0.20 / kelime", distanceKm: 7.9,
    },
    {
        id: "p-023", displayName: "Berk Özkan", providerType: "Serbest Uzman",
        headline: "Güvenlik kamera ve alarm sistemi kurulumu",
        summary: "IP kamera, alarm ve akıllı ev güvenlik sistemleri. Hikvision, Dahua yetkili servisi.",
        categoryIds: ["repair"], locationScope: "Sultangazi, İstanbul",
        rating: 4.4, completedJobs: 92, responseTime: "aynı gün", servesNearby: false,
        tags: ["güvenlik", "kamera", "alarm", "ip kamera", "akıllı ev", "kurulum"],
        photoUrl: "", priceRange: "₺1.500 - ₺6.000 / sistem", distanceKm: 14.6,
    },
    {
        id: "p-024", displayName: "Aslı Tunç", providerType: "Serbest Uzman",
        headline: "Yoga eğitmeni — hatha, vinyasa ve meditasyon",
        summary: "Başlangıç ve orta seviye yoga, meditasyon seansları. Birebir veya grup.",
        categoryIds: ["beauty", "education"], locationScope: "Cihangir, İstanbul",
        rating: 4.8, completedJobs: 132, responseTime: "30 dk", servesNearby: true,
        tags: ["yoga", "meditasyon", "hatha", "vinyasa", "pilates", "nefes"],
        photoUrl: "", priceRange: "₺350 - ₺700 / seans", distanceKm: 1.8,
    },
    {
        id: "p-025", displayName: "Sercan Bayrak", providerType: "Serbest Uzman",
        headline: "Mutfak ve banyo tadilat ustası",
        summary: "Mutfak ve banyo komple renovasyon. Fayans, seramik, ankastre kurulum.",
        categoryIds: ["repair"], locationScope: "Kartal, İstanbul",
        rating: 4.7, completedJobs: 113, responseTime: "2 saat", servesNearby: false,
        tags: ["mutfak", "banyo", "tadilat", "fayans", "seramik", "renovasyon"],
        photoUrl: "", priceRange: "₺4.000 - ₺18.000 / oda", distanceKm: 12.1,
    },
    {
        id: "p-026", displayName: "Tuğçe Aksoy", providerType: "Serbest Uzman",
        headline: "Sosyal medya yöneticisi ve içerik üreticisi",
        summary: "Instagram, TikTok, LinkedIn hesap yönetimi ve reklam ajanlığı.",
        categoryIds: ["creative", "digital"], locationScope: "Bakırköy, İstanbul",
        rating: 4.6, completedJobs: 58, responseTime: "1 saat", servesNearby: false,
        tags: ["sosyal medya", "instagram", "tiktok", "içerik", "yönetim", "marka"],
        photoUrl: "", priceRange: "₺2.000 - ₺5.500 / ay", distanceKm: 8.7,
    },
    {
        id: "p-027", displayName: "Volkan Tekin", providerType: "Serbest Uzman",
        headline: "Çatı tamiri ve su yalıtım uzmanı",
        summary: "Çatı aktarma, kiremit değişimi, su yalıtımı. Uzun garantili işçilik.",
        categoryIds: ["repair"], locationScope: "Eyüpsultan, İstanbul",
        rating: 4.5, completedJobs: 88, responseTime: "aynı gün", servesNearby: false,
        tags: ["çatı", "tamiri", "yalıtım", "su yalıtımı", "kiremit", "sızdırmazlık"],
        photoUrl: "", priceRange: "₺2.500 - ₺12.000 / çatı", distanceKm: 11.3,
    },
    {
        id: "p-028", displayName: "Mine Ay", providerType: "Serbest Uzman",
        headline: "Çocuk bakıcısı ve oyun ablası (0-8 yaş)",
        summary: "Evde çocuk bakımı, eğitici oyun ve gelişim aktiviteleri.",
        categoryIds: ["beauty"], locationScope: "Zeytinburnu, İstanbul",
        rating: 4.8, completedJobs: 176, responseTime: "20 dk", servesNearby: true,
        tags: ["çocuk bakımı", "bebek", "oyun ablası", "eğitici oyun", "günlük bakım"],
        photoUrl: "", priceRange: "₺200 - ₺450 / gün", distanceKm: 5.6,
    },
    {
        id: "p-029", displayName: "Cenk Ateş", providerType: "Serbest Uzman",
        headline: "Evden eve nakliyat ve eşya taşıma",
        summary: "Kırılmaz paketleme, güvenli eşya taşıma. İstanbul içi ve şehirlerarası.",
        categoryIds: ["delivery"], locationScope: "Bahçelievler, İstanbul",
        rating: 4.4, completedJobs: 267, responseTime: "aynı gün", servesNearby: false,
        tags: ["nakliyat", "taşıma", "eşya", "evden eve", "paketleme", "asansör"],
        photoUrl: "", priceRange: "₺1.200 - ₺4.500 / taşıma", distanceKm: 9.4,
    },
    {
        id: "p-030", displayName: "Leyla Kapucu", providerType: "Serbest Uzman",
        headline: "Klinik psikolog — bireysel ve ilişki terapisi",
        summary: "Anksiyete, depresyon, ilişki sorunları için bireysel terapi. Yüz yüze ve online.",
        categoryIds: ["beauty"], locationScope: "Nişantaşı, İstanbul",
        rating: 4.9, completedJobs: 210, responseTime: "1 saat", servesNearby: false,
        tags: ["psikoloji", "terapi", "anksiyete", "depresyon", "terapist", "ilişki"],
        photoUrl: "", priceRange: "₺600 - ₺1.200 / seans", distanceKm: 4.8,
    },
    {
        id: "p-031", displayName: "Erdem Başar", providerType: "Serbest Uzman",
        headline: "Marangoz — ahşap mobilya ve doğrama imalatı",
        summary: "Özel ölçü şifonyer, dolap, raf sistemi ve ahşap merdiven. Tasarım ve imalat bir arada.",
        categoryIds: ["repair"], locationScope: "Sancaktepe, İstanbul",
        rating: 4.7, completedJobs: 74, responseTime: "2 saat", servesNearby: false,
        tags: ["marangoz", "ahşap", "doğrama", "mobilya", "dolap", "ahşap doğrama"],
        photoUrl: "", priceRange: "₺2.000 - ₺10.000 / parça", distanceKm: 13.8,
    },
    {
        id: "p-032", displayName: "İpek Yılmaz", providerType: "Serbest Uzman",
        headline: "Piyano dersleri — her yaş ve seviye",
        summary: "Konservatuvar mezunu piyano öğretmeni. Klasik, caz ve pop. 5-75 yaş.",
        categoryIds: ["education"], locationScope: "Moda, İstanbul",
        rating: 4.9, completedJobs: 156, responseTime: "aynı gün", servesNearby: true,
        tags: ["piyano", "müzik", "enstrüman", "klasik", "ders", "müzik teorisi"],
        photoUrl: "", priceRange: "₺400 - ₺750 / saat", distanceKm: 2.3,
    },
    {
        id: "p-033", displayName: "Selim Akkaya", providerType: "Serbest Uzman",
        headline: "DevOps mühendisi — AWS, Kubernetes ve CI/CD",
        summary: "Bulut altyapısı kurulumu, container yönetimi, pipeline otomasyonu.",
        categoryIds: ["digital"], locationScope: "Maslak, İstanbul",
        rating: 4.8, completedJobs: 29, responseTime: "3 saat", servesNearby: false,
        tags: ["DevOps", "AWS", "kubernetes", "cloud", "CI/CD", "bulut"],
        photoUrl: "", priceRange: "₺12.000 - ₺40.000 / proje", distanceKm: 7.1,
    },
    {
        id: "p-034", displayName: "Reyhan Şahin", providerType: "Serbest Uzman",
        headline: "Makyaj sanatçısı — gelin, nişan ve özel gün",
        summary: "Düğün, nişan ve özel günler için profesyonel makyaj. HD, airbrush uygulamaları.",
        categoryIds: ["beauty"], locationScope: "Üsküdar, İstanbul",
        rating: 4.9, completedJobs: 234, responseTime: "15 dk", servesNearby: true,
        tags: ["makyaj", "gelin", "kalıcı makyaj", "düğün", "airbrush", "makyaj sanatçısı"],
        photoUrl: "", priceRange: "₺800 - ₺2.500 / seans", distanceKm: 3.5,
    },
    {
        id: "p-035", displayName: "Oğuz Çavuşoğlu", providerType: "Serbest Uzman",
        headline: "Kombi bakım ve doğalgaz tesisatı uzmanı",
        summary: "Yıllık kombi bakımı, revizyon, doğalgaz tesisatı ve radyatör kurulum.",
        categoryIds: ["repair"], locationScope: "Kadıköy, İstanbul",
        rating: 4.6, completedJobs: 198, responseTime: "25 dk", servesNearby: true,
        tags: ["kombi", "bakım", "doğalgaz", "tesisatı", "radyatör", "kalorifer"],
        photoUrl: "", priceRange: "₺400 - ₺1.600 / bakım", distanceKm: 1.9,
    },
    {
        id: "p-036", displayName: "Sıla Eroğlu", providerType: "Serbest Uzman",
        headline: "E-ticaret danışmanı — Trendyol, Hepsiburada, Amazon",
        summary: "Mağaza açılışı, ürün listeleme, reklam optimizasyonu ve satış danışmanlığı.",
        categoryIds: ["consulting", "digital"], locationScope: "Sarıyer, İstanbul",
        rating: 4.7, completedJobs: 47, responseTime: "1 saat", servesNearby: false,
        tags: ["e-ticaret", "trendyol", "amazon", "satış", "mağaza", "danışmanlık"],
        photoUrl: "", priceRange: "₺2.000 - ₺7.000 / ay", distanceKm: 10.2,
    },
    {
        id: "p-037", displayName: "Faruk Karahan", providerType: "Serbest Uzman",
        headline: "Su tesisatı — tıkanıklık açma ve pimaş yıkama",
        summary: "Lavabo, küvet ve tuvalet tıkanıklığı açma, pimaş yıkama, su kaçağı tespiti.",
        categoryIds: ["repair"], locationScope: "Gaziosmanpaşa, İstanbul",
        rating: 4.5, completedJobs: 389, responseTime: "10 dk", servesNearby: true,
        tags: ["su tesisatı", "tıkanıklık", "pimaş", "borular", "su kaçağı", "tesisatçı"],
        photoUrl: "", priceRange: "₺250 - ₺800 / işlem", distanceKm: 9.7,
    },
    {
        id: "p-038", displayName: "Bengü Öztürk", providerType: "Serbest Uzman",
        headline: "Dans eğitmeni — salsa, bachata ve latin dans",
        summary: "Yetişkin ve çocuklara latin dansları. Bireysel ve grup dersler.",
        categoryIds: ["education", "beauty"], locationScope: "Beşiktaş, İstanbul",
        rating: 4.8, completedJobs: 118, responseTime: "2 saat", servesNearby: false,
        tags: ["dans", "salsa", "bachata", "latin", "tango", "eğitmen"],
        photoUrl: "", priceRange: "₺350 - ₺650 / saat", distanceKm: 2.6,
    },
    {
        id: "p-039", displayName: "Onur Koç", providerType: "Serbest Uzman",
        headline: "iOS & Android mobil uygulama geliştirici",
        summary: "Swift, Kotlin ve React Native ile native ve cross-platform mobil uygulamalar.",
        categoryIds: ["digital"], locationScope: "Ataşehir, İstanbul",
        rating: 4.7, completedJobs: 31, responseTime: "4 saat", servesNearby: false,
        tags: ["mobil", "ios", "android", "uygulama", "swift", "react native"],
        photoUrl: "", priceRange: "₺15.000 - ₺60.000 / uygulama", distanceKm: 8.3,
    },
    {
        id: "p-040", displayName: "Hazal Kaya", providerType: "Serbest Uzman",
        headline: "Fotoğrafçılık kursu ve atölye çalışmaları",
        summary: "DSLR başlangıç, Lightroom, Photoshop eğitimi. Bireysel veya küçük grup.",
        categoryIds: ["education", "creative"], locationScope: "Cihangir, İstanbul",
        rating: 4.7, completedJobs: 82, responseTime: "3 saat", servesNearby: false,
        tags: ["fotoğraf", "kurs", "atölye", "lightroom", "photoshop", "eğitim"],
        photoUrl: "", priceRange: "₺500 - ₺1.200 / saat", distanceKm: 1.5,
    },
    {
        id: "p-041", displayName: "Arda Güner", providerType: "Serbest Uzman",
        headline: "Kapı ve pencere tamiri, PVC doğrama",
        summary: "Çelik kapı, PVC pencere, alüminyum doğrama onarım ve değişimi.",
        categoryIds: ["repair"], locationScope: "Tuzla, İstanbul",
        rating: 4.4, completedJobs: 164, responseTime: "aynı gün", servesNearby: false,
        tags: ["kapı", "pencere", "PVC", "doğrama", "kilit", "çelik kapı"],
        photoUrl: "", priceRange: "₺200 - ₺1.500 / işlem", distanceKm: 22.7,
    },
    {
        id: "p-042", displayName: "Tuğba Yıldız", providerType: "Serbest Uzman",
        headline: "Halı, koltuk ve döşeme yıkama — eve geliyorum",
        summary: "Makine ile koltuk döşeme yıkama, halı yıkama ve perde temizliği.",
        categoryIds: ["cleaning"], locationScope: "Bağcılar, İstanbul",
        rating: 4.6, completedJobs: 231, responseTime: "1 saat", servesNearby: true,
        tags: ["halı yıkama", "koltuk", "döşeme", "perde", "temizlik", "yıkama"],
        photoUrl: "", priceRange: "₺300 - ₺800 / parça", distanceKm: 6.1,
    },
    {
        id: "p-043", displayName: "Sinan Polat", providerType: "Serbest Uzman",
        headline: "Avukat — iş hukuku ve kira uyuşmazlıkları",
        summary: "İş hukuku, kira hukuku, sözleşme hazırlama ve hukuki danışmanlık.",
        categoryIds: ["consulting"], locationScope: "Bakırköy, İstanbul",
        rating: 4.8, completedJobs: 95, responseTime: "2 saat", servesNearby: false,
        tags: ["avukat", "hukuk", "danışmanlık", "kira", "iş hukuku", "sözleşme"],
        photoUrl: "", priceRange: "₺800 - ₺2.500 / saat", distanceKm: 7.5,
    },
    {
        id: "p-044", displayName: "Bahar Korkmaz", providerType: "Serbest Uzman",
        headline: "Marka ve logo tasarımı, kurumsal kimlik paketi",
        summary: "Startup ve işletmeler için logo, kurumsal kimlik ve sosyal medya şablonları.",
        categoryIds: ["creative"], locationScope: "Şişli, İstanbul",
        rating: 4.9, completedJobs: 107, responseTime: "2 saat", servesNearby: false,
        tags: ["logo", "marka", "kurumsal kimlik", "tasarım", "kartvizit", "renk paleti"],
        photoUrl: "", priceRange: "₺2.000 - ₺7.500 / paket", distanceKm: 4.3,
    },
    {
        id: "p-045", displayName: "Koray Demirci", providerType: "Serbest Uzman",
        headline: "Oto detaylı temizlik ve araç kozmetiği",
        summary: "İç dış detaylı araç temizliği, nano seramik kaplama, pasta cila.",
        categoryIds: ["cleaning"], locationScope: "Bayrampaşa, İstanbul",
        rating: 4.5, completedJobs: 193, responseTime: "30 dk", servesNearby: true,
        tags: ["araç temizliği", "oto", "detaylı", "seramik kaplama", "cila", "boya koruma"],
        photoUrl: "", priceRange: "₺400 - ₺3.500 / araç", distanceKm: 5.9,
    },
    {
        id: "p-046", displayName: "Yıldız Ercan", providerType: "Serbest Uzman",
        headline: "Satranç eğitmeni — FIDE üyesi",
        summary: "Başlangıçtan turnuva seviyesine satranç eğitimi. 7-18 yaş, yetişkin.",
        categoryIds: ["education"], locationScope: "Üsküdar, İstanbul",
        rating: 4.8, completedJobs: 143, responseTime: "aynı gün", servesNearby: false,
        tags: ["satranç", "eğitmen", "FIDE", "turnuva", "akıl oyunları", "koçluk"],
        photoUrl: "", priceRange: "₺350 - ₺700 / saat", distanceKm: 8.0,
    },
    {
        id: "p-047", displayName: "Taner Öz", providerType: "Serbest Uzman",
        headline: "Alçıpan, asma tavan ve kartonpiyer ustası",
        summary: "Alçıpan bölme duvar, asma tavan, kartonpiyer ve dekoratif sıva.",
        categoryIds: ["repair"], locationScope: "Kâğıthane, İstanbul",
        rating: 4.6, completedJobs: 127, responseTime: "2 saat", servesNearby: false,
        tags: ["alçıpan", "asma tavan", "kartonpiyer", "bölme duvar", "sıva", "tavan"],
        photoUrl: "", priceRange: "₺250 - ₺600 / m²", distanceKm: 10.4,
    },
    {
        id: "p-048", displayName: "Özge Sönmez", providerType: "Serbest Uzman",
        headline: "İşletme ve strateji danışmanı — KOBİ uzmanı",
        summary: "İş planı, pazar araştırması, finansal modelleme ve büyüme stratejisi.",
        categoryIds: ["consulting"], locationScope: "Levent, İstanbul",
        rating: 4.8, completedJobs: 42, responseTime: "3 saat", servesNearby: false,
        tags: ["danışmanlık", "strateji", "iş planı", "yönetim", "KOBİ", "büyüme"],
        photoUrl: "", priceRange: "₺3.000 - ₺12.000 / proje", distanceKm: 6.4,
    },
    {
        id: "p-049", displayName: "Alp Güvener", providerType: "Serbest Uzman",
        headline: "Akıllı ev ve IoT sistemleri kurulumu",
        summary: "Zigbee, Z-Wave ve WiFi destekli akıllı ev otomasyon sistemleri.",
        categoryIds: ["repair", "digital"], locationScope: "Şişli, İstanbul",
        rating: 4.7, completedJobs: 53, responseTime: "3 saat", servesNearby: false,
        tags: ["akıllı ev", "IoT", "otomasyon", "aydınlatma", "güvenlik sistemleri", "kurulum"],
        photoUrl: "", priceRange: "₺2.500 - ₺15.000 / sistem", distanceKm: 5.0,
    },
    {
        id: "p-050", displayName: "Şeyma Tok", providerType: "Serbest Uzman",
        headline: "Pasta yapımı eğitmeni ve özel sipariş pasta",
        summary: "Şeker hamuru, fondant, naked cake yapımı atölyesi. Sipariş pasta da alınır.",
        categoryIds: ["education"], locationScope: "Pendik, İstanbul",
        rating: 4.7, completedJobs: 91, responseTime: "aynı gün", servesNearby: true,
        tags: ["pasta", "kek", "atölye", "fondant", "şeker hamuru", "el sanatları"],
        photoUrl: "", priceRange: "₺400 - ₺900 / atölye", distanceKm: 16.3,
    },
    {
        id: "p-051", displayName: "Canan Doğru", providerType: "Serbest Uzman",
        headline: "Muhasebeci ve mali müşavir — KOBİ'ler için",
        summary: "Aylık muhasebe, vergi beyannamesi, SGK işlemleri.",
        categoryIds: ["consulting"], locationScope: "Kadıköy, İstanbul",
        rating: 4.8, completedJobs: 86, responseTime: "2 saat", servesNearby: false,
        tags: ["muhasebe", "mali müşavir", "vergi", "SGK", "beyanname", "finans"],
        photoUrl: "", priceRange: "₺1.500 - ₺4.000 / ay", distanceKm: 2.5,
    },
    {
        id: "p-052", displayName: "Doğan Yıldızoğlu", providerType: "Serbest Uzman",
        headline: "Fizyoterapist — evde rehabilitasyon",
        summary: "Bel, boyun, diz ağrısı tedavisi ve spor yaralanmalarında manuel terapi.",
        categoryIds: ["beauty"], locationScope: "Kadıköy, İstanbul",
        rating: 4.9, completedJobs: 167, responseTime: "1 saat", servesNearby: true,
        tags: ["fizyoterapi", "rehabilitasyon", "bel ağrısı", "spor", "manuel terapi"],
        photoUrl: "", priceRange: "₺600 - ₺1.200 / seans", distanceKm: 3.1,
    },
    {
        id: "p-053", displayName: "Kaan Erdoğan", providerType: "Serbest Uzman",
        headline: "Video kurgucu ve YouTube içerik üreticisi",
        summary: "Premiere Pro, DaVinci Resolve ile profesyonel video montaj. Color grading.",
        categoryIds: ["creative"], locationScope: "Beyoğlu, İstanbul",
        rating: 4.7, completedJobs: 78, responseTime: "4 saat", servesNearby: false,
        tags: ["video kurgu", "youtube", "premiere", "daVinci", "color grading", "montaj"],
        photoUrl: "", priceRange: "₺1.500 - ₺6.000 / video", distanceKm: 2.2,
    },
    // ── Dynamic / user-created categories (not in the predefined tree) ─────────
    {
        id: "p-054", displayName: "Emir Balcı", providerType: "Serbest Uzman",
        headline: "Drone ile gayrimenkul ve etkinlik çekimi",
        summary: "İnşaat takibi, gayrimenkul tanıtımı ve etkinlikler için lisanslı drone pilotu. 4K hava görüntüsü.",
        categoryIds: ["drone-cekim", "creative"], locationScope: "İstanbul geneli",
        rating: 4.8, completedJobs: 27, responseTime: "3 saat", servesNearby: false,
        tags: ["drone", "hava çekimi", "lisanslı pilot", "4K"],
        photoUrl: "", priceRange: "₺1.200 - ₺3.000 / çekim", distanceKm: 5.4,
    },
    {
        id: "p-055", displayName: "Pelin Aksoy", providerType: "Serbest Uzman",
        headline: "Müzik prodüksiyon ve şarkı aranjmanı",
        summary: "Stüdyo kalitesinde aranjman, mix ve mastering. Jingle, podcast müziği ve sanatçı demoları.",
        categoryIds: ["muzik-produksiyon"], locationScope: "Kadıköy stüdyo + uzaktan",
        rating: 4.9, completedJobs: 44, responseTime: "1 gün", servesNearby: false,
        tags: ["müzik", "prodüksiyon", "mix mastering", "aranjman"],
        photoUrl: "", priceRange: "₺800 - ₺2.500 / parça", distanceKm: 2.6,
    },
    {
        id: "p-056", displayName: "Onur Kaptan", providerType: "Serbest Uzman",
        headline: "Tekne bakım, temizlik ve sezon hazırlığı",
        summary: "Yat ve tekneler için polyester onarımı, dip boyası, motor bakımı ve detaylı temizlik. Marina içi.",
        categoryIds: ["tekne-bakim"], locationScope: "Fenerbahçe & Kalamış Marina",
        rating: 4.7, completedJobs: 19, responseTime: "2 gün", servesNearby: false,
        tags: ["tekne", "yat bakımı", "marina", "polyester"],
        photoUrl: "", priceRange: "₺1.500 - ₺6.000 / iş", distanceKm: 6.1,
    },
    {
        id: "p-057", displayName: "Sevgi Demirtaş", providerType: "Serbest Uzman",
        headline: "Butik pasta ve özel gün tasarım kek",
        summary: "Doğum günü, nişan ve kurumsal etkinlikler için özel tasarım pastalar. Şeker hamuru ve glütensiz.",
        categoryIds: ["pasta-tasarim", "events"], locationScope: "Bahçeşehir + çevre ilçeler",
        rating: 4.9, completedJobs: 61, responseTime: "aynı gün", servesNearby: true,
        tags: ["pasta", "tasarım kek", "özel gün", "glütensiz"],
        photoUrl: "", priceRange: "₺400 - ₺1.800 / sipariş", distanceKm: 3.3,
    },
];

// ── Friendly labels for dynamic / user-created category ids ──────────────────
export const DYNAMIC_CATEGORY_LABELS: Record<string, string> = {
    "drone-cekim": "Drone Çekim",
    "muzik-produksiyon": "Müzik Prodüksiyon",
    "tekne-bakim": "Tekne & Yat Bakımı",
    "pasta-tasarim": "Butik Pasta & Tasarım Kek",
};

// ── Static Businesses ────────────────────────────────────────────────────────
export const STATIC_BUSINESSES: BusinessView[] = [
    {
        id: "b-001", tradeName: "CleanPro Temizlik", providerType: "İşletme",
        sector: "Profesyonel Temizlik Hizmetleri",
        summary: "Ev, ofis ve inşaat sonrası temizlik. Sigortlı ekiplerle 7/24.",
        categoryIds: ["cleaning"], locationScope: "Beşiktaş, İstanbul",
        rating: 4.7, completedJobs: 1243, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺450 - ₺1.200 / seans", distanceKm: 2.3,
    },
    {
        id: "b-002", tradeName: "TekServis Elektrik", providerType: "İşletme",
        sector: "Elektrik Tesisatı ve Bakım",
        summary: "Konut ve ticari alanlarda elektrik tesisatı, pano yenileme, LED aydınlatma.",
        categoryIds: ["repair"], locationScope: "Bağcılar, İstanbul",
        rating: 4.5, completedJobs: 567, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺500 - ₺3.500 / iş", distanceKm: 6.8,
    },
    {
        id: "b-003", tradeName: "DigitalKlon Ajans", providerType: "İşletme",
        sector: "Dijital Pazarlama ve Web Geliştirme",
        summary: "Web tasarım, SEO, sosyal medya ve dijital reklamcılık.",
        categoryIds: ["digital", "creative"], locationScope: "Levent, İstanbul",
        rating: 4.6, completedJobs: 287, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺3.000 - ₺15.000 / ay", distanceKm: 5.1,
    },
    {
        id: "b-004", tradeName: "AkademiHocam Eğitim", providerType: "İşletme",
        sector: "Özel Eğitim ve Mentorluk",
        summary: "YKS, LGS, KPSS ve dil sınavları için online ve yüz yüze dersler.",
        categoryIds: ["education"], locationScope: "Kadıköy, İstanbul",
        rating: 4.8, completedJobs: 3420, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺250 - ₺550 / saat", distanceKm: 3.7,
    },
    {
        id: "b-005", tradeName: "PetEvim Hayvan Bakımevi", providerType: "İşletme",
        sector: "Evcil Hayvan Bakım ve Konaklama",
        summary: "Köpek, kedi ve küçük hayvanlar için 7/24 otel ve grooming.",
        categoryIds: ["pets"], locationScope: "Sarıyer, İstanbul",
        rating: 4.8, completedJobs: 768, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺250 - ₺600 / gece", distanceKm: 9.6,
    },
    {
        id: "b-006", tradeName: "BuildMaster Tadilatçı", providerType: "İşletme",
        sector: "İnşaat ve Genel Tadilat",
        summary: "Komple daire/ofis tadilat, alçıpan, fayans, boya. Anahtar teslim.",
        categoryIds: ["repair"], locationScope: "Esenyurt, İstanbul",
        rating: 4.4, completedJobs: 183, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺15.000 - ₺80.000 / proje", distanceKm: 17.2,
    },
    {
        id: "b-007", tradeName: "FotografyaStüdyosu", providerType: "İşletme",
        sector: "Fotoğrafçılık ve Görüntü Prodüksiyonu",
        summary: "Ürün, moda, kurumsal ve etkinlik fotoğrafçılığı. 300m² stüdyo.",
        categoryIds: ["creative"], locationScope: "Maslak, İstanbul",
        rating: 4.7, completedJobs: 412, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺2.500 - ₺12.000 / gün", distanceKm: 7.3,
    },
    {
        id: "b-008", tradeName: "EventStudio Organizasyon", providerType: "İşletme",
        sector: "Etkinlik Planlama ve Organizasyon",
        summary: "Düğün, kurumsal toplantı, konser ve özel etkinlik organizasyonu.",
        categoryIds: ["events"], locationScope: "Şişli, İstanbul",
        rating: 4.7, completedJobs: 234, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺8.000 - ₺50.000 / etkinlik", distanceKm: 4.5,
    },
    {
        id: "b-009", tradeName: "SağlıklıYaşam Merkezi", providerType: "İşletme",
        sector: "Wellness ve Kişisel Gelişim",
        summary: "Pilates, yoga, meditasyon, masaj ve beslenme danışmanlığı.",
        categoryIds: ["beauty", "education"], locationScope: "Etiler, İstanbul",
        rating: 4.9, completedJobs: 897, responseTime: "1 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺500 - ₺1.500 / ay", distanceKm: 3.4,
    },
    {
        id: "b-010", tradeName: "YükselLojistik", providerType: "İşletme",
        sector: "Kargo ve Nakliyat",
        summary: "Şehir içi ve şehirlerarası kurye, evden eve nakliyat. 50+ araç filosu.",
        categoryIds: ["delivery"], locationScope: "Bağcılar, İstanbul",
        rating: 4.3, completedJobs: 4521, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺150 - ₺3.500 / teslimat", distanceKm: 8.2,
    },
    {
        id: "b-011", tradeName: "MimarProje Ofisi", providerType: "İşletme",
        sector: "Mimari ve İç Mekan Tasarımı",
        summary: "Konut, ticari ve kurumsal mimari proje, iç mekan tasarımı.",
        categoryIds: ["consulting", "creative"], locationScope: "Nişantaşı, İstanbul",
        rating: 4.8, completedJobs: 94, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺8.000 - ₺40.000 / proje", distanceKm: 4.1,
    },
    {
        id: "b-012", tradeName: "HukukDanış Hukuk Bürosu", providerType: "İşletme",
        sector: "Hukuki Danışmanlık ve Avukatlık",
        summary: "Ticaret hukuku, gayrimenkul, iş hukuku ve aile hukuku.",
        categoryIds: ["consulting"], locationScope: "Levent, İstanbul",
        rating: 4.7, completedJobs: 312, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺1.200 - ₺4.500 / saat", distanceKm: 5.9,
    },
    {
        id: "b-013", tradeName: "MüzikEvi Sanat Okulu", providerType: "İşletme",
        sector: "Müzik Eğitimi ve Sanat Okulu",
        summary: "Gitar, piyano, keman, vokal ve davul dersleri. Her yaşa özel programlar.",
        categoryIds: ["education"], locationScope: "Beşiktaş, İstanbul",
        rating: 4.8, completedJobs: 1678, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺400 - ₺900 / ay", distanceKm: 2.8,
    },
    {
        id: "b-014", tradeName: "GreenGarden Peyzaj", providerType: "İşletme",
        sector: "Bahçe ve Peyzaj Tasarımı",
        summary: "Villa, site ve ofis bahçesi tasarımı ve bakımı. Sulama sistemleri.",
        categoryIds: ["repair"], locationScope: "Zekeriyaköy, İstanbul",
        rating: 4.6, completedJobs: 127, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺3.000 - ₺20.000 / bahçe", distanceKm: 24.1,
    },
    {
        id: "b-015", tradeName: "ChefEvde Catering", providerType: "İşletme",
        sector: "Özel Yemek ve Catering",
        summary: "Düğün, kokteyl ve kurumsal etkinliklere özel menü ve catering.",
        categoryIds: ["events"], locationScope: "Fatih, İstanbul",
        rating: 4.7, completedJobs: 286, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺150 - ₺450 / kişi", distanceKm: 5.7,
    },
    {
        id: "b-016", tradeName: "SafeHome Güvenlik", providerType: "İşletme",
        sector: "Güvenlik Sistemleri ve İzleme",
        summary: "IP kamera, alarm, akıllı kilit ve 7/24 uzaktan izleme.",
        categoryIds: ["repair"], locationScope: "Bahçelievler, İstanbul",
        rating: 4.5, completedJobs: 342, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺2.500 - ₺8.000 / sistem", distanceKm: 9.3,
    },
    {
        id: "b-017", tradeName: "GümüşKalem Tercüme", providerType: "İşletme",
        sector: "Çeviri ve Tercümanlık",
        summary: "40+ dilde yeminli ve teknik çeviri. Sözleşme, patent ve akademik metin.",
        categoryIds: ["consulting"], locationScope: "Beyoğlu, İstanbul",
        rating: 4.8, completedJobs: 1892, responseTime: "aynı gün",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺0.06 - ₺0.18 / kelime", distanceKm: 2.9,
    },
    {
        id: "b-018", tradeName: "TeknoFix Bilgisayar", providerType: "İşletme",
        sector: "Bilgisayar Tamir ve Teknik Destek",
        summary: "Laptop, masaüstü, Mac onarımı. Veri kurtarma, yazılım kurulum.",
        categoryIds: ["digital"], locationScope: "Şişli, İstanbul",
        rating: 4.5, completedJobs: 876, responseTime: "2 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺200 - ₺2.500 / işlem", distanceKm: 3.6,
    },
    {
        id: "b-019", tradeName: "HızlıKurye Express", providerType: "İşletme",
        sector: "Kurye ve Hızlı Teslimat",
        summary: "İstanbul geneli 1 saatte teslimat garantisi. Soğuk zincir ve ilaç dağıtımı.",
        categoryIds: ["delivery"], locationScope: "Ataşehir, İstanbul",
        rating: 4.6, completedJobs: 6789, responseTime: "10 dk",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺60 - ₺280 / teslimat", distanceKm: 7.8,
    },
    {
        id: "b-020", tradeName: "NailArt Studio", providerType: "İşletme",
        sector: "Tırnak Sanatı ve Güzellik",
        summary: "Manikür, pedikür, nail art, jel ve akrilik tırnak tasarımı.",
        categoryIds: ["beauty"], locationScope: "Nişantaşı, İstanbul",
        rating: 4.8, completedJobs: 1124, responseTime: "1 saat",
        verificationStatus: "APPROVED", photoUrl: "", priceRange: "₺200 - ₺800 / seans", distanceKm: 5.2,
    },
];
