package app.viaverse.identity.shared.audit;

public enum IdentityAuditEventEnum {
    ACCOUNT_CREATED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    PASSWORD_LOGIN_SUCCEEDED,
    PASSWORD_LOGIN_FAILED,
    OTP_VERIFIED,
    OTP_FAILED,
    SOCIAL_SIGN_IN_SUCCEEDED,
    REFRESH_TOKEN_ROTATED,
    REFRESH_TOKEN_REUSED,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT,
    SESSION_REVOKED,
    CONSENT_ACCEPTED,
    PASSWORD_CHANGED,
    TWO_FACTOR_ENROLL_STARTED,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_DISABLED,
    TWO_FACTOR_VERIFIED,
    TWO_FACTOR_VERIFY_FAILED
}
